New project. Sprint #13
ilya2012gvy/java-shareit pull request #1
Opened 2023-06-14 17:21 UTC by ilya2012gvy

2023-06-20 16:46 UTC, Donald522 requested changes
привет!

Все хорошо, оставил несколько замечаний по неймингу

2023-06-20 16:46 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    List<Item> findUserById(long id);
Название метода странное, и  не соответствует сигнатуре

2023-06-20 16:46 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    List<Item> searchText(String text);
searchByText?

2023-06-20 16:46 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +            if (!Objects.equals(items.get(id).getOwner(), user)) {
Название исключения не совсем соответствует действительности.
Тут проверяется, что юзер обновляет свой же предмет, а не чужой.
Странно видеть исключение ItemExistsException из метода update. Наличие предмета это необходимое условие для его обновления, а не ошибка

2023-06-20 16:46 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +        return false;
Почему тут всегда false возвращается?

2023-06-20 16:46 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +public class ItemController {
Давай логировния добавим

2023-06-20 16:46 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +    List<User> listUsers();
Обычно такое называют findAll

2023-06-20 16:46 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +    User findUserById(long id);
User лишнее в названии. По сигнатуре понятно, что ищется

2023-06-20 16:46 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +                .anyMatch(user1 -> user1.getEmail().equals(user.getEmail()))) {
user1 плохое название
лучше existingUser

2023-06-20 16:46 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +                throw new UserExistsException("Пользователь уже существует!");
Тут то же замечание, что в и ItemRepository

2023-06-20 18:01 UTC, ilya2012gvy commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +public class ItemController {
Привет, если логирование есть на уровне Repository, зачем дублировать?

2023-06-21 17:29 UTC, Donald522 approved these changes
Привет!

Поправь, пожалуйста, к след спринту названия методов и исключение, которое бросается из UserRepository

2023-06-21 17:29 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +public class ItemController {
На get запросах там нет логирования.
Ну и репозиторий все таки не лучшее место для логирования. До репозитория запрос может и не дойти

2023-06-21 17:29 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    List<Item> getAllItems(long id);
Опять же название - getAll не предполагает передачу параметров в него.
Что возвращает этот метод? Что за id он принимает?

2023-06-21 18:57 UTC, merged